### ISSUE TITLE
move_base / navfn planner failures in fuerte, groovy (not hydro)

### ISSUE THREAD

**Issue by tkruse** [ros-planning/navigation#102] opened 2013-08-02 13:08 UTC
Hi,

in our environment we notice occasional invalid plans created by move_base. I set up a tiny rosbuild package with a stage config and a move_base config based on the navigation_tutorials/navigation_stage package here:
https://github.com/tkruse/adream_stage

There are two failures occuring regularly enough to be reproduced, globals plans passing through walls (https://github.com/tkruse/adream_stage/blob/master/images/fail_wall.png) and global plans starting halfway to the goal (https://github.com/tkruse/adream_stage/blob/master/images/fail_halfway.png).

The images are contained in the github project, and the green line shows the invalid global path.

To reproduce, in fuerte, install all dependencies of the package, then run 

```
roslaunch adream_stage adream_stage.launch
```

I could not get this to reproduce for every single time we plan, but i set the planning frequency to 10, so every time I run a fresh roscore and plan roughly like in the images, I can see the halfway plan bug, and every 2nd time or so I observe the plan going through the wall.

Note that in order to reproduce, I use to often kill all the roslaunch file and start again from the initial situation.

This might of course be a bad parameters issue, if so please advise which parameter may be causing this.

In Groovy, I could observe the planning through walls still, but not planning from a halfway position. in Hydro, I could not observe any problems, so maybe you'll close this issue as "fixed". Maybe you can still recommend some solution for fuerte users, e.g. using latest navigation stack from source in fuerte.

**Comment by tkruse** [comment] 2013-08-02 14:15
Hm, planning through walls may somehow be caused by this:
http://answers.ros.org/question/54559/navfn-stability/

though not sure how this would happen in stage.

**Comment by DLu** [comment] 2013-08-02 17:49
In Hydro, the static map is not overwritten. 

I haven't checked your particular parameters, but often obstacle_range is shorter than raytrace_range, meaning a wall can be cleared if mis-localized, but the relevant marking observations will not be added back.

**Comment by hershwg** [comment] 2013-08-02 18:02
This is two separate bugs, both fixed.  Closing.

First bug, the incomplete plan bug, is a duplicate of either #16 or #18.  Both were fixed in Groovy.

Second bug, planning paths through walls, is fixed by the switch in Hydro to layered-costmaps in which the static map is not overwritten by sensor data.  As @DLu  mentioned, before hydro this could be caused by raytrace_range being shorter than obstacle_range combined with unreliable sensor data.  So, this is definitely fixed in hydro and can potentially be worked around in earlier versions by looking carefully at your global costmap parameters and sensor data.

**Closed as completed by hershwg** 2013-08-02 18:02 UTC
