### ISSUE TITLE
base_local_planner MapGridCostPoint should use EIGEN_MAKE_ALIGNED_OPERATOR_NEW

### ISSUE THREAD

**Issue by efernandez** [ros-planning/navigation#135] opened 2013-10-10 11:05 UTC
I've this error when using DWA planner:

<pre>
move_base: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:69: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = float, int Size = 4, int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(array) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
</pre>

And this is the callstack:

<pre>
[...]
 7:  __kernel_vsyscall
/lib/i386-linux-gnu/libc.so.6:
 8:  gsignal
 9:  abort
Not found,  linked without -rdynamic?10:  
Not found,  linked without -rdynamic?11:  
costmap_2d/lib/libcostmap_2d.so:
12:  Eigen::internal::plain_array<float, 4, 0, 16>::plain_array()
13:  Eigen::DenseStorage<float, 4, 4, 1, 0>::DenseStorage(int, int, int)
14:  Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1, 0, 4, 1> >::PlainObjectBase(int, int, int)
15:  Eigen::Matrix<float, 4, 1, 0, 4, 1>::Matrix<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, 4, 1, 0, 4, 1> > >(Eigen::MatrixBase<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, 4, 1, 0, 4, 1> > > const&)
base_local_planner/lib/libbase_local_planner.so:
16:  pcl::PointCloud<base_local_planner::MapGridCostPoint>::PointCloud()
17:  base_local_planner::MapGridVisualizer::MapGridVisualizer()
dwa_local_planner/lib/libdwa_local_planner.so:
18:  dwa_local_planner::DWAPlanner::DWAPlanner(std::string, costmap_2d::Costmap2DROS*)
19:  dwa_local_planner::DWAPlannerROS::initialize(std::string, tf::TransformListener*, costmap_2d::Costmap2DROS*)
/home/enriquefernandez/branches_svn/OROCOS_2.X/stacks/navigation/move_base/bin/move_base:
20:  move_base::MoveBase::MoveBase(std::string, tf::TransformListener&)
21:  main
/lib/i386-linux-gnu/libc.so.6:
22:  __libc_start_main
</pre>

The problem happens in ROS fuerte, but the code affected is the same in fuerte and hydro (see below):

<pre>
roscd base_local_planner
vim include/base_local_planner/map_grid_cost_point.h
</pre>

The MapGridCostPoint should be as follows:

<pre>
    struct EIGEN_ALIGN16 MapGridCostPoint {
        PCL_ADD_POINT4D;
        float path_cost;
        float goal_cost;
        float occ_cost;
        float total_cost;

        EIGEN_MAKE_ALIGNED_OPERATOR_NEW
    };
</pre>

as the other points defined in pcl:

<pre>
cd /opt/ros/${ROS_DISTRO}/include/pcl-1.5/pcl
vim impl/point_types.hpp
</pre>

IMHO, it's strange that this didn't happen before to somebody else. Anyway, after comparing the points definitions in pcl, it looks like the point struct defined in map_grid_cost_point.h should be as above. I've made that change and the problem disappeared.

**Comment by DLu** [comment] 2013-10-14 17:10
Seems plausible that this is related to #122 . Is there any good documentation on using EIGEN_MAKE_ALIGNED_OPERATOR_NEW with pcl?

**Comment by felix-kolbe** [comment] 2013-10-15 14:39
Confirmed on fresh clone of groovy-devel-catkinized compiled clean running on groovy/12.04, with the difference that my message states `reinterpret_cast<size_t>` instead of just `reinterpret_cast`. Oh and: not using any DWA but the other one.

**Comment by DLu** [comment] 2013-10-17 15:33
Are these errors occurring on 32 or 64 bit machines?

**Comment by felix-kolbe** [comment] 2013-10-17 16:26
Good point. For me: 32 bit SW on 64 bit HW, unfortunately cannot use 64 bit.

**Comment by efernandez** [comment] 2013-10-17 17:38
Same for me: 32bit SW on 64bit HW.

<pre>
$ uname -m
i686
</pre>

**Comment by efernandez** [comment] 2013-10-21 09:46
I've adapted the code to use EIGEN_MAKE_ALIGNED_OPERATOR_NEW. Basically, you have to add it to the classes that use the MapGridCostPoint point as a member. Here is a patch for fuerte (actually after the initial change to MapGridCostPoint above). I've been using the base local planner for some time after that and it seems to be stable. I think this only affects 32bit SW. It will be great if this is also included in hydro; indeed, I could also provide a clean patch for hydro in some weeks.

<pre>
===================================================================
--- base_local_planner/include/base_local_planner/map_grid_cost_point.h
+++ base_local_planner/include/base_local_planner/map_grid_cost_point.h
@@ -37,7 +37,7 @@
 #include <pcl/ros/register_point_struct.h>
 
 namespace base_local_planner {
-    struct EIGEN_ALIGN16 MapGridCostPoint {
+    struct EIGEN_ALIGN16 _MapGridCostPoint {
         PCL_ADD_POINT4D;
         float path_cost;
         float goal_cost;
@@ -46,15 +46,30 @@
 
         EIGEN_MAKE_ALIGNED_OPERATOR_NEW
     };
+
+    struct EIGEN_ALIGN16 MapGridCostPoint : public _MapGridCostPoint
+    {
+        inline MapGridCostPoint()
+        {
+            x = y = z = 0.0f;
+            data[3] = 1.0f;
+            path_cost = goal_cost = occ_cost = total_cost = 0.0f;
+        }
+
+        EIGEN_MAKE_ALIGNED_OPERATOR_NEW
+    };
 }
 
-POINT_CLOUD_REGISTER_POINT_STRUCT(
-        base_local_planner::MapGridCostPoint,
+POINT_CLOUD_REGISTER_POINT_STRUCT(base_local_planner::_MapGridCostPoint,
         (float, x, x)
         (float, y, y)
         (float, z, z)
         (float, path_cost, path_cost)
         (float, goal_cost, goal_cost)
         (float, occ_cost, occ_cost)
-        (float, total_cost, total_cost));
+        (float, total_cost, total_cost)
+)
+
+POINT_CLOUD_REGISTER_POINT_WRAPPER(base_local_planner::MapGridCostPoint, base_local_planner::_MapGridCostPoint)
+
 #endif
===================================================================
--- base_local_planner/include/base_local_planner/map_grid_visualizer.h
+++ base_local_planner/include/base_local_planner/map_grid_visualizer.h
@@ -43,6 +43,8 @@
 namespace base_local_planner {
     class MapGridVisualizer {
         public:
+            EIGEN_MAKE_ALIGNED_OPERATOR_NEW
+
             /**
               * @brief Default constructor
               */
===================================================================
--- base_local_planner/include/base_local_planner/trajectory_planner_ros.h
+++ base_local_planner/include/base_local_planner/trajectory_planner_ros.h
@@ -77,6 +77,8 @@
    */
   class TrajectoryPlannerROS : public nav_core::BaseLocalPlanner {
     public:
+      EIGEN_MAKE_ALIGNED_OPERATOR_NEW
+
       /**
        * @brief  Default constructor for the ros wrapper
        */
===================================================================
--- dwa_local_planner/include/dwa_local_planner/dwa_planner.h
+++ dwa_local_planner/include/dwa_local_planner/dwa_planner.h
@@ -62,6 +62,8 @@
    */
   class DWAPlanner {
     public:
+      EIGEN_MAKE_ALIGNED_OPERATOR_NEW
+
       /**
        * @brief  Constructor for the planner
        * @param name The name of the planner 
===================================================================
--- dwa_local_planner/include/dwa_local_planner/dwa_planner_ros.h
+++ dwa_local_planner/include/dwa_local_planner/dwa_planner_ros.h
@@ -48,6 +48,8 @@
    */
   class DWAPlannerROS : public nav_core::BaseLocalPlanner {
     public:
+      EIGEN_MAKE_ALIGNED_OPERATOR_NEW
+
       /**
        * @brief  Constructor for DWAPlannerROS wrapper
        */
</pre>

**Comment by felix-kolbe** [comment] 2013-10-21 16:44
When I compile in groovy:

```
In file included from /home/demo/catkin_ws/src/navigation/base_local_planner/include/base_local_planner/map_grid_visualizer.h:40:0,
                 from /home/demo/catkin_ws/src/navigation/base_local_planner/src/map_grid_visualizer.cpp:34:
/home/demo/catkin_ws/src/navigation/base_local_planner/include/base_local_planner/map_grid_cost_point.h: In constructor ‘base_local_planner::MapGridCostPoint::MapGridCostPoint()’:
/home/demo/catkin_ws/src/navigation/base_local_planner/include/base_local_planner/map_grid_cost_point.h:56:13: error: ‘data’ was not declared in this scope
/home/demo/catkin_ws/src/navigation/base_local_planner/include/base_local_planner/map_grid_cost_point.h: At global scope:
/home/demo/catkin_ws/src/navigation/base_local_planner/include/base_local_planner/map_grid_cost_point.h:74:1: error: no matching function for call to ‘assertion_failed(mpl_::failed************ (POINT_WRAPPER_AND_POD_TYPES_HAVE_DIFFERENT_SIZES::************)(base_local_planner::MapGridCostPoint&, base_local_planner::_MapGridCostPoint&))’
/home/demo/catkin_ws/src/navigation/base_local_planner/include/base_local_planner/map_grid_cost_point.h:74:1: note: candidate is:
/usr/include/boost/mpl/assert.hpp:79:5: note: template<bool C> int mpl_::assertion_failed(typename mpl_::assert<C>::type)
make[2]: *** [navigation/base_local_planner/CMakeFiles/base_local_planner.dir/src/map_grid_visualizer.cpp.o] Error 1
```

The first one goes away if I remove the "data[3]..." line, but the second problem persists. I don't even know why removing "data" works, the [map_grid_cost_point.h](https://github.com/ros-planning/navigation/commits/navigation-1.8/base_local_planner/include/base_local_planner/map_grid_cost_point.h) has never changed. I've never used PCL or Eigen directly.. do you have any hints for groovy?

**Comment by efernandez** [comment] 2013-10-22 07:44
Note that I modified map_grid_cost_point.h in order to define the _MapGridCostPoint struct as the points in PCL. That's why we have data[3], coming from the PCL_ADD_POINT4D macro.

I think the second error is also coming from the fact that I change _MapGridCostPoint in that way, probably the EIGEN_ALIGN16. See my first comment. I modify the struct in map_grid_cost_point.h. Then I applied the diff of my last message.

If you want I can pass you the modified files, but they're for ROS fuerte. I prefer to wait and test it on hydro. Then I'd like to see if it makes sense to have this for 64bit. Finally, at least for 32bit, I think it should be used, so I'll create a pull request.

**Comment by felix-kolbe** [comment] 2013-10-29 17:40
Oh, I searched for but overlooked the PCL_ADD_POINT4D macro. I tried removing your underscored duplicate and adding the operator macro, but it doesn't suffice. Maybe it needs to say I'm running navigation from fuerte-debs (because navigation from groovy-debs has a tf issue for me), and that without problem, so there must be another thing different in code. Going to live with it.

**Comment by rbrusu** [comment] 2013-11-07 18:39
http://eigen.tuxfamily.org/dox-devel/group__TopicStructHavingEigenMembers.html talks a bit more about why these macros are needed on 32bit architectures. As the Eigen-dev team describes it: "No, it's not our bug. It's more like an inherent problem of the C++98 language specification, and seems to be taken care of in the upcoming language revision: see this document." 

Unfortunately we all have to live with it unless we upgrade our compilers or our machines to 64bit. An alternative would be to disable vectorization altogether, but that would make the code much slower than it already is.

**Comment by DLu** [comment] 2013-11-07 21:11
@rbrusu Is there a canonical example for how to use these Eigen structures with PCL?

**Comment by rbrusu** [comment] 2013-11-07 21:19
There is a tutorial here (http://pointclouds.org/documentation/tutorials/adding_custom_ptype.php) that talks about how to add a new point type, and the example given uses EIGEN_MAKE_ALIGNED_OPERATOR_NEW. Other than that, I'm not sure. Contributions that improve this part of the documentation will be appreciated.

**Comment by yhchuah2** [comment] 2015-01-14 05:58
I adapted my code totally the same as suggested by @efernandez but the error is still exist. I am running move_base in groovy and ubuntu 12.04. Is there any other solution? I need to run move_base node for my final year project.

**Comment by efernandez** [comment] 2015-01-14 08:11
@yhchuah2 You can try with 64bit, so you don't have this kind of issues.
I guess you're using 32bit, right?
Where is the code you're using?
Latest version from here works for me on 32bit.

**Comment by yhchuah2** [comment] 2015-01-14 11:49
Here are my code:

base_local_planner/include/base_local_planner/map_grid_cost_point.h:
namespace base_local_planner {
    struct EIGEN_ALIGN16 _MapGridCostPoint {
    PCL_ADD_POINT4D;        

```
    float path_cost;
    float goal_cost;
    float occ_cost;
    float total_cost;

EIGEN_MAKE_ALIGNED_OPERATOR_NEW

};
```

struct EIGEN_ALIGN16 MapGridCostPoint : public _MapGridCostPoint
    {
        inline MapGridCostPoint()
        {
            x = y = z = 0.0f;
            data[3] = 1.0f;
            path_cost = goal_cost = occ_cost = total_cost = 0.0f;
        }

```
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};
```

}

POINT_CLOUD_REGISTER_POINT_STRUCT(base_local_planner::_MapGridCostPoint,
        (float, x, x)
        (float, y, y)
        (float, z, z)
        (float, path_cost, path_cost)
        (float, goal_cost, goal_cost)
        (float, occ_cost, occ_cost)
        (float, total_cost, total_cost)
)
POINT_CLOUD_REGISTER_POINT_WRAPPER(base_local_planner::MapGridCostPoint, base_local_planner::_MapGridCostPoint)
#endif

---

base_local_planner/include/base_local_planner/map_grid_visualizer.h:
namespace base_local_planner {
    class MapGridVisualizer {
        public:
        EIGEN_MAKE_ALIGNED_OPERATOR_NEW

```
        /**
          * @brief Default constructor
          */
```

---

base_local_planner/include/base_local_planner/trajectory_planner_ros.h:
namespace base_local_planner {
  /**
- @class TrajectoryPlannerROS
- @brief A ROS wrapper for the trajectory controller that queries the param server to construct a controller
  */
  class TrajectoryPlannerROS : public nav_core::BaseLocalPlanner {
    public:
     EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  
  ```
  /**
   * @brief  Default constructor for the ros wrapper
   */
  ```
  
  ---

dwa_local_planner/include/dwa_local_planner/dwa_planner.h:
namespace dwa_local_planner {
  /**
- @class DWAPlanner
- @brief A class implementing a local planner using the Dynamic Window Approach
  */
  class DWAPlanner {
    public:
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  
  ```
  /**
   * @brief  Constructor for the planner
   * @param name The name of the planner 
   * @param costmap_ros A pointer to the costmap instance the planner should use
   * @param global_frame the frame id of the tf frame to use
   */
  ```
  
  ---

dwa_local_planner/include/dwa_local_planner/dwa_planner.ros.h:
namespace dwa_local_planner {
  /**
- @class DWAPlannerROS
- @brief ROS Wrapper for the DWAPlanner that adheres to the
- BaseLocalPlanner interface and can be used as a plugin for move_base.
  */
  class DWAPlannerROS : public nav_core::BaseLocalPlanner {
    public:
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  
  ```
  /**
   * @brief  Constructor for DWAPlannerROS wrapper
   */
  ```
  
  ---

Yes I am using 32 bit system, change to 64 bit system means install a new version of ubuntu? My current version of ubuntu is 12.04, may I know which version is 64 bit? I might install a parallel OS if necessary.

**Comment by mikeferguson** [comment] 2017-08-01 07:17
Going to close this as "will not fix". We've got some folks in the community who are helping to move us to tf2 and off PCL altogether (which will make this completely irrelevant). In the meantime, newer ROS releases have also dropped much of their 32-bit support.

**Closed as completed by mikeferguson** 2017-08-01 07:17 UTC
Labels: bug, planners
