### ISSUE TITLE
Planning while action server is active

### ISSUE THREAD

**Issue by dtaranta** [ros-planning/navigation#967] opened 2020-02-21 09:59 UTC
Is there any reason for move_base not letting to plan a new goal while the action server is active? [here](https://github.com/ros-planning/navigation/blob/melodic-devel/move_base/src/move_base.cpp#L342)

I've got a situation where I need to plan to an alternative goal while the robot is moving. I commented that condition and it seems to work fine. Maybe there is a reason I'm not aware?

**Comment by DLu** [comment] 2020-02-27 22:55
The service doesn't use the planner_mutex, so checking the action server works as a proxy.

**Comment by mikeferguson** [comment] 2020-03-29 14:21
Duplicate of https://github.com/ros-planning/navigation/issues/12

**Closed as completed by mikeferguson** 2020-03-29 14:21 UTC
