### ISSUE TITLE
Error in move base:  

### ISSUE THREAD

**Issue by rnunziata** [ros-planning/navigation#122] opened 2013-09-03 22:32 UTC
Laser Pose= -7.03812 2.5283 0.0750175
[ INFO] [1378214170.838243980, 421.260000000]: Using plugin "obstacle_layer"
[ INFO] [1378214171.187628217, 421.319000000]:     Subscribed to Topics: laser_scan_sensor
[ INFO] [1378214171.285210319, 421.331000000]: Using plugin "footprint_layer"
[ INFO] [1378214171.321360203, 421.336000000]: Using plugin "inflation_layer"
move_base: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:69: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = float, int Size = 4, int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(array) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/TopicUnalignedArrayAssert.html" " ***\* READ THIS WEB PAGE !!! ***_"' failed.
[move_base-7] process has died [pid 22711, exit code -6, cmd /opt/ros/hydro/lib/move_base/move_base __name:=move_base __log:=/home/rnunziata/.ros/log/5f2afbc4-1499-11e3-80f9-000c29589865/move_base-7.log].
log file: /home/rnunziata/.ros/log/5f2afbc4-1499-11e3-80f9-000c29589865/move_base-7_.log

**Comment by rnunziata** [comment] 2013-09-03 22:33
This error could be due to incorrect config file setting but I am unable to determine what is in error. Please let me know if I can supply any additional data.

**Comment by rnunziata** [comment] 2013-09-03 22:34
Sorry did not mean to close this issue.

**Comment by DLu** [comment] 2013-09-04 17:03
Which version of the code are you using? This looks like a duplicate of #105

**Comment by rnunziata** [comment] 2013-09-04 18:38
I am using hydro. I never used move_base before. I am running on VMWare on an MacPro osx 10.8.
I do not know if this is a duplicate or not I am up-todate so if it is fixed and not released then I can not test it.

**Comment by rnunziata** [comment] 2013-09-08 13:24
Does anyone have a workaround for this bug. I can not move forward with my project until I get pass this.

**Comment by DLu** [comment] 2013-09-08 21:43
How did you obtain the code you are using? From the debians? Or did you download the code yourself?

**Comment by rnunziata** [comment] 2013-09-09 04:09
I downloaded move base and other packages using ubuntu software manager , some time I will issue apt-get upgrade on the command line after that. I set the repository as:

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'

**Comment by DLu** [comment] 2013-09-09 16:14
The duplicate issue mentioned above fixed an error similar to this about a month ago in the source. Please do an upgrade to be sure you are using the fixed version.

**Comment by rnunziata** [comment] 2013-09-09 17:27
I did an upgrade very recently...if by upgrade we mean "sudo apt-get upgrade". And it did pull ros packages so ...I believe I am current. What was the cause of the previous issue that was similar? Is there anything I can do to debug it locally?

**Comment by rnunziata** [comment] 2013-09-10 21:12
Do you think there would be any benefit if I compiled move_base from source?

**Comment by mikeferguson** [comment] 2017-08-01 18:27
Per #135, will not further fix

**Closed as completed by mikeferguson** 2017-08-01 18:27 UTC
Labels: bug, move_base

**Comment by Misaka10046** [comment] 2019-08-21 03:06
Have you solved this problem?  I haven't figured out what happening since I encountered this problem 3 days before. And I can't move forward my programme because of this problem,too.

**Comment by kanishkanarch** [comment] 2021-09-03 09:15
@Misaka10046 Were you able to solve the problem? I'm having `exit code 11`
