### ISSUE TITLE
static_layer cause costmap wrong when map size is changed

### ISSUE THREAD

**Issue by tongsky723** [ros-planning/navigation#924] opened 2019-09-24 08:15 UTC
When I used gmapping to create map while move base is running. Costmap became wrong when map size is changed.
As you can see from following pictures. Second one costmap became wrong when map is resized!
 
![2019-09-24 16-11-01 的屏幕截图](https://user-images.githubusercontent.com/28940801/65493812-2f5d5180-dee6-11e9-81cf-416563117c9f.png)
![2019-09-24 16-11-14 的屏幕截图](https://user-images.githubusercontent.com/28940801/65493818-32f0d880-dee6-11e9-8baf-863ff6f64102.png)

**Comment by mikeferguson** [comment] 2020-02-13 15:20
I believe this is a duplicate of #959

**Closed as completed by mikeferguson** 2020-02-13 15:20 UTC
Labels: bug, costmap_2d
