### ISSUE TITLE
Support for TrajectoryPlannerROS in Hydro

### ISSUE THREAD

**Issue by mintar** [ros-planning/navigation#36] opened 2013-05-05 13:34 UTC
Please keep support for TrajectoryPlannerROS after merging the layered-costmaps code mentioned in [this ros-users announcement](http://code.ros.org/lurker/message/20130503.161202.6460e19c.en.html). It is essential for our getting navigation to work on our diff-drive, non-holonomic robot. The dwa_local_planner may be fine on a holonomic robot, but on non-holonomic robots it always ends up commanding a straight sideways motion (x and yaw vel = 0, y vel > 0), but our robot can't move sideways, so it gets stuck. (This is just one extreme case of problems caused by a y velocity planned by DWA, but ignored by our controller; we must have a local planner that only uses x and yaw).

**Comment by corot** [comment] 2013-05-06 02:53
I notice the same: DWA on hydro-devel is terrible.
Trajectory Rollout works as expected.

**Comment by mintar** [comment] 2013-05-06 09:29
@corot: That's not what I meant. What I meant was that I've used TrajectoryPlannerROS so far (in Fuerte), and I would like to keep using it. DWA works fine on holonomic robots.

**Comment by hershwg** [comment] 2013-05-06 20:29
It is looking like supporting most of the stuff in the "not ready yet" list (including TrajectoryPlannerROS) is going to be possible, as David Lu is helping out a bunch.

I do find it very interesting that TrajectoryPlannerROS is seen as the solution for diff-drive robots.  I've used DWAPlannerROS for a diff-drive machine a bunch and had it work fine.  The thing is, both TrajectoryPlannerROS and DWAPlannerROS have a lot of parameters to adjust their behavior.

For diff-drive with DWA, some of the important parameters are:

```
  acc_lim_y: 0 # diff-drive can't accelerate in y direction at all
  max_vel_y: 0 # also can't have any velocity in y direction
  min_vel_y: 0
  vy_samples: 0 # don't take any samples from the y direction
```

At their core, TrajectoryPlannerROS and DWAPlannerROS both do the same thing: roll out future base motions for a set time duration in a costmap and choose the one with the lowest cost.  According to Eitan (who wrote it originally), DWAPlannerROS was intended as a cleaner rewrite of TrajectoryPlannerROS.

@corot I'm interested in hearing about bugs in DWA.

**Comment by corot** [comment] 2013-05-07 01:22
Ha...  sorry mintar; I misunderstood your comment.

Hershwg, DWA works ok when I set all y-speed related parameters to 0, as you suggested. I gave for granted that base_local_planner just ignored them when holonomic_robot is false.

However, robot moves much slower than with traj. rollout, most of the time below the max vel values. So I'm much happier with TR by now. I'm very short of time now to investigate what I'm doing wrong, but I'll do as soon as I have enough time.

**Comment by mintar** [comment] 2013-05-07 06:20
@hershwg I just dug through my git history to check which of the parameters you mentioned we missed when we were still using DWA. The answer is "all of them", so I guess that explains it. :-)

Thanks for the info, good to know how that switching to DWA is an option. This makes me feel much less strongly about this ticket, so feel free to put it on the back burner if it's a lot of hassle.

**Comment by hershwg** [comment] 2013-05-07 16:27
Well, I know tuning move_base is a lot of work. I would like to make the groovy to hydro transition not _require_ you all to do that work.  Progress on TrajectoryPlannerROS etc is going well, so I expect it will be largely unaffected by the time we release Hydro.

**Comment by hershwg** [comment] 2013-07-03 22:08
TrajectoryPlannerROS was ported to the new layered costmap API and a bunch of backwards-compatibility work was done, closing.

**Closed as completed by hershwg** 2013-07-03 22:08 UTC
