### ISSUE TITLE
Costmap_2d doesn't get the right sensor_frame from sensor messages

### ISSUE THREAD

**Issue by corot** [ros-planning/navigation#148] opened 2013-11-08 03:53 UTC
According to ros wiki, if parameter sensor_frame is not set for an observation source, it will be read from sensor data, but somehow this value changes to /map!.

I didn't trace the bug, but just print values:

```
  //check whether the origin frame has been set explicitly or whether we should get it from the cloud
  ROS_ERROR(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   %s    %s", sensor_frame_.c_str(), cloud.header.frame_id.c_str());
  string origin_frame = sensor_frame_ == "" ? cloud.header.frame_id : sensor_frame_;
```

An to my surprise I take this

```
[/move_base]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   /laser_link    map
```

If I don't set sensor_frame parameter I get an empty string instead of /laser_link, frame is set as map, and in the log appears continuously this warning:

```
[/move_base]: The origin for the sensor at (0.00, 0.00, 0.00) is out of map bounds. So, the costmap cannot raytrace for it.
```

and the costmap doesn't get updated.

This happens for the first time, after pull the last changes, so I think it must be a recent regression. Also, with the released navi stack all works fine, as usually.

Btw, I keep using old stile costmap configuration.

**Comment by corot** [comment] 2013-11-13 09:52
I will not pull req the change by now, until someone can confirm that I'm nor reverting an intended change.

**Comment by mikeferguson** [comment] 2014-02-08 01:49
+1, I am seeing this with a source checkout of 1.11.5 (but did not see it with latest debs).

That doesn't seem to be the right fix, as I see no reason to do a transform from frame X to X.

@DLu any thoughts on what is going on? If I don't set the sensor_frame for my laser with the latest source, I end up with tons of: 

```
 [ WARN] [1391822720.465979604]: The origin for the sensor at (0.00, 0.00, 0.00) is out of map bounds. So, the costmap cannot raytrace for it.
```

Which rosconsole blames on:

```
 /home/fergs/nav_test/src/navigation/costmap_2d/plugins/voxel_layer.cpp:VoxelLayer::raytraceFreespace:242
```

**Comment by DLu** [comment] 2014-02-11 22:44
Not sure quite what I did, but I thought 1.11.5 was ready for release, but then when I went to make the debs, it failed some tests. I am investigating, and will get back to you.

**Comment by DLu** [comment] 2014-02-12 02:12
Alrighty. I'm not sure what change caused the problem, but I think I understand what's going on. 

The costmap needs to know where the sensor is to be able to clear between it and the reading. It puts the sensor at 0,0,0 in some frame, either the specified sensor frame or the data's frame, as per the line you quoted. 

However, all of the sensor info goes through a message filter , transforming it into map coordinates before it reaches the observation buffer, causing the cloud to have the '/map' frame. 

The code to filter the sensor data goes back to 2010, so I don't think it's anything I've done recently. Is there a easy minimum example that I can test with?

**Comment by mikeferguson** [comment] 2014-02-12 03:43
This code has definitely changed in the last several months, [the exact commit is here](https://github.com/ros-planning/navigation/commit/6532c847d7ef3ee828b38cc6d3ac757ae4790906#diff-917783c15e528bed37e271a944d6714bL196)

This commit changes the transformed point cloud to be in the global frame, rather than the message frame. In fact, after this point, I presume the message frame is entirely lost -- hence we cannot compute where the sensor 0,0,0 is.

The issue here is that the cloud (in the global frame) is then added to the observation buffer. See that [observation_buffer.cpp line 138](https://github.com/ros-planning/navigation/blob/hydro-devel/costmap_2d/src/observation_buffer.cpp#L138) will use point 0,0,0, in cloud.header.frame_id (which is now the global frame!) as the sensor origin.

It is my opinion we should revert the original change in transforming the laserscan to the global_frame_ in the callback -- especially since the [ObservationBuffer will already do that transformation](https://github.com/ros-planning/navigation/blob/hydro-devel/costmap_2d/src/observation_buffer.cpp#L156). We should probably also remove the waitForTransform that was added, as it will be handled later on in the ObservationBuffer.

**Comment by DLu** [comment] 2014-02-12 04:03
Ah ok. I misread the situation. 

The code originally comes from the Groovy branch in my repo via https://github.com/DLu/navigation/pull/4 and @ZdenekM . (Original discussion here: https://github.com/DLu/navigation/pull/3) I clearly did not realize the implications of the change, so thanks to both of you for pointing it out. 

I am in favor of changing back, unless there's something criticial in @ZdenekM's use case.

**Comment by mikeferguson** [comment] 2014-02-12 04:11
I don't see how this change is related to the discussion of a min_range, or how reverting it would affect the use of a min_range either. As for improving efficiency, it really doesn't as the ObservationBuffer is still going to do this transformation, and we can't really remove that from the ObservationBuffer class or you'd break PointCloud sensor functionality.

**Comment by DLu** [comment] 2014-02-12 17:55
Ok. I rolled back that change. Let me know if the new version works as intended, and then we can close the issue and I'll release a new version number.

**Closed as completed** 2014-02-12 17:55 UTC
Labels: bug, costmap_2d

**Comment by ZdenekM** [comment] 2014-02-19 09:12
Hmm, sorry for breaking stuff. Original idea was to transform laser scan in correct way as transformLaserScanToPointCloud should be used with some "fixed reference frame" ([API description](http://ftp.isr.ist.utl.pt/pub/roswiki/doc/electric/api/laser_geometry/html/classlaser__geometry_1_1LaserProjection.html#abd41a10eaab5463c424d47a8328efb4d), [Tully's explanation here](http://answers.ros.org/question/42459/fixed-target-frame-for-transformlaserscantopointcloud/?answer=42631#post-id-42631)). If this method is used with sensor frame, it doesn't make much sense. Then it would be better (faster) to use projectLaser method. This can be essential for fast moving robot (with slowly spinning laser). In our case it was bit problematic with 2D laser simulated from Velodyne data.

**Comment by DLu** [comment] 2014-02-20 19:47
Did anyone else get a chance to test the code?

**Comment by mikeferguson** [comment] 2014-02-20 22:02
I can run a test later today.

**Comment by mikeferguson** [comment] 2014-02-21 03:15
Just tested hydro-devel branch, all looks good here.
