### ISSUE TITLE
Problems while testing layered costmaps in hydro-devel

### ISSUE THREAD

**Issue by piyushk** [ros-planning/navigation#60] opened 2013-05-28 03:18 UTC
I was testing the eband_local_planner against hydro-devel branch to give a shot at the layered_costmap feature. I've encountered a few problems trying to get it layered costmaps to work appropriately that I'll try and explain here:

Configuration:
[Common Costmap Parameters](https://github.com/utexas-bwi/segbot_apps/blob/master/segbot_navigation/config/eband/costmap_common_params.yaml)
[Global Costmap Parameters](https://github.com/utexas-bwi/segbot_apps/blob/master/segbot_navigation/config/eband/global_costmap_params.yaml)
[Local Costmap Parameters](https://github.com/utexas-bwi/segbot_apps/blob/master/segbot_navigation/config/eband/local_costmap_params.yaml)
[Map](https://github.com/utexas-bwi/bwi_experimental/blob/master/utexas_gdc/maps/3ne.yaml)

Here's a [video](http://farnsworth.csres.utexas.edu/share/final.ogv) (75MB) showing rviz output. I first show the underlying map, then the local costmap (0:18) and then the global costmap (0:44). I had the following questions:
1. The global costmap looks as expected. However, it does not seem to be taking into account the new box I've placed in. I know that the global costmap is working fine, as navfn is taking that box into account, but I am not sure why the visualization is off.
2. The local costmap appears to be pretty broken. Whenever I query a cost in the local costmap, I always get a value of freespace unless I have run into an obstacle. There seem to be no interim values. This is problematic as the eband approach requires knowing the distance of a point to the closest obstacle (which works on the groovy debs). Consequently, the robot appears to be running blind.
3. The voxel grid seems to be correct at all times. There are a few spurious radings here or there, but I am not sure if those are simulation issues or not. 

I'll try and provide whatever information is necessary to figure this out.

**Comment by hershwg** [comment] 2013-05-28 17:25
Thanks for the report.

The new layered costmap code natively wants a list of plugins ("layers") which implement different things, like there is a layer for the static map, a layer for voxels, a layer for inflation, etc.  Using the "plugins" ros param, you give it a list of these layers you want to use.  For backwards compatibility with peoples' old navigation configurations, @DLu added code which detects the lack of the "plugins" parameter and attempts to build a set of layers that mimics the behavior of the old system.  When it does this, it actually puts the parameters on the parameter server, so you can see the result of the translation.

It sounds to me like these bugs might be caused by bad rosparam translations.  Can you do the following?
- Launch your nav config with Groovy navigation
- While it is running, in another terminal do `rosparam get /move_base > groovy-nav-config.yaml`
- Kill it.
- Launch your nav config with Hydro navigation
- While it is running, in another terminal do `rosparam get /move_base > hydro-nav-config.yaml`

Then post here the contents of groovy-nav-config.yaml and hydro-nav-config.yaml.

**Comment by piyushk** [comment] 2013-05-29 07:44
@hershwg I ran your steps and for the conversion seemed fine. Let me know if you still want me to post the results.

I spent a bit of time figuring out the error. Excuse the closed pull request. There are a few problems with that. I'll submit an improved pull request in the morning.

I had a bit more time right now to look into the code. Here's my take on what was going wrong:
1. The OccupancyGrid published was taking the uchar values from the costmap directly, but they need to be 0-100 with -1 for unknown. I'll submit a pull request in the morning with the fix.
2. The parameter robot_radius needs to be set inside move_base. It appears that the hydro-devel costmap constructs a footprint based on this radius. I didn't have this set in groovy, and as far as I can tell the footprint was fine.
3. While testing out hydro-devel, I forgot what inflation_radius was and managed to set it to the inscribed_radius value, and was not inflating proximity information to obstacles causing navigation to fail. Note that this value can be computed automatically given the cost scaling factor and inscribed radius. I was wondering if there was a reason why the user has to select this value. If you're interested, I can submit a patch to automate the computation (I have most of the code written down already).

Hope this helps!

**Comment by hershwg** [comment] 2013-05-29 18:11
Re (1) from the first message, I believe the problem is that the global costmap is only published once at the start, and after that only OccupancyGridUpdate messages are published.  These are smaller messages which are much more efficient to send than the entire grid.  The new Costmap display plugin for rviz reads these, but the "map" display you are using does not know about them.
1. The costmap plugin expects the published OccupancyGrid messages to have its data range from 0 to 255 by default.  If we translate all the values from 0:255 to -1:100 we will lose information about the costmaps that the planners are using and thus it will hamper debugging efforts.  To obey message definitions properly, I think a better action is to make a new message, "Costmap" and define that to match the data that is already being published.  I have opened #64 to track this.
2. Hydro navigation adds the ability of costmaps to subscribe to the robot footprint instead of just reading it from a ros-param.  For backwards-compatibility, if move_base finds a footprint parameter it reads it and then publishes it.  Apparently this now behaves a bit different from the old way.  I created issue #63 to track this.
3. Indeed inflation_radius is an important parameter.  This value should not be computed automatically, as that would give much larger inflations than people typically need, and inflation is very computationally expensive.  The value you get from an automatic computation could be an upper bound, but for instance with the value of 3 that I usually use for weight_, your formula gives an inflation radius of over 2 meters.  I've been using 1 meter and may reduce it further.  My own feeling on this is that it would be better to have the "costmap" class just compute a distance field instead of a "cost" field, then the planners could interpret the distances as they like.  With the new pluggable costmap layers, this is now pretty feasible to implement as a new layer to replace the existing inflation layer.

I'm closing this bug, as #63 and #64 contain the specific changes needed, and the inflation_radius problem was not a bug.

**Closed as completed by hershwg** 2013-05-29 18:11 UTC

**Comment by piyushk** [comment] 2013-05-29 18:28
@hershwg Thanks for the excellent explanation. It makes a lot of sense to me.

I did get my local planner to behave correctly once I made the (albeit incorrect) changes in my pull request. This leads me to believe that once #63 and #64 are fixed, my code should run in a backwards compatible manner. I'll verify this and then update my parameter configuration to hydro.

**Comment by DLu** [comment] 2013-05-31 19:19
Just as an additional note, I struggled with how best to define the semantics of the OccupancyGrid w.r.t. the costmap awhile ago (http://comments.gmane.org/gmane.science.robotics.ros.user/16934) and decided in this case to overload the definition of the OccupancyGrid as it is published by costmap_publisher so as not to define another message type. I agree that another message type that uses a different rviz plugin would be the best solution.
